import dotenv from "dotenv";

dotenv.config();

export const config = {
  PORT: Number(process.env.PORT),
  HOST: process.env.HOST,
  MONGO_URL: process.env.MONGO_URL,
  HASH_PASSWORD_ROUNDS: Number(process.env.HASH_PASSWORD_ROUNDS),
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRES_IN: process.env.ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN: process.env.REFRESH_TOKEN_EXPIRES_IN,
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  SENDGRID_FROM_EMAIL: process.env.SENDGRID_FROM_EMAIL,
  ADMIN_EMAIL: process.env.ADMIN_EMAIL,
  MANAGER_EMAIL: process.env.MANAGER_EMAIL,
  MAX_PROFANITY_EDITS: Number(process.env.MAX_PROFANITY_EDITS),
  ACTION_TOKEN_SETUP_MANAGER_SECRET:
    process.env.ACTION_TOKEN_SETUP_MANAGER_SECRET,
  ACTION_TOKEN_SETUP_MANAGER_EXPIRES_IN:
    process.env.ACTION_TOKEN_SETUP_MANAGER_EXPIRES_IN,
  ACTION_TOKEN_FORGOT_PASSWORD_SECRET:
    process.env.ACTION_TOKEN_FORGOT_PASSWORD_SECRET,
  ACTION_TOKEN_FORGOT_PASSWORD_EXPIRES_IN:
    process.env.ACTION_TOKEN_FORGOT_PASSWORD_EXPIRES_IN,
  FRONT_URL: process.env.FRONT_URL,
  DEFAULT_MANAGER_PASSWORD: process.env.DEFAULT_MANAGER_PASSWORD,
  API_PRIVATBANK: process.env.API_PRIVATBANK,
};
